#include <cmath>
#include "Constants.hpp"
#include "Solver.hpp"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif // M_PI

Solver::Solver()
{
  mT << 0, 0, 0;
  mEta << 0, 0, 0;
  mMu << 0, 0, 0;
  mDt = 0;
  mTCol << 0, 0, 0;
  mShip = NULL;
}

Solver::Solver(Ship* aShip)
{
  mT << 0, 0, 0;
  mEta << 0, 0, 0;
  mMu << 0, 0, 0;
  mDt = 0;
  Init(aShip);
}


int Solver::Init(Ship* aShip)
{
  int ret=0;
  
  if(NULL != aShip)
    mShip = aShip;
  else
    ret=-1;

  return ret;
}

Eigen::VectorXd Solver::DiffEq(const Eigen::VectorXd& aVectEtaMu)
{
  const Eigen::Vector3d vEta(aVectEtaMu[0],aVectEtaMu[1],aVectEtaMu[2]);
  const Eigen::Vector3d vMu(aVectEtaMu[3],aVectEtaMu[4],aVectEtaMu[5]);
  Eigen::Matrix3d matRotPsi;
  Eigen::Matrix3d matC;
  Eigen::Vector3d vEtaP;
  Eigen::Vector3d vMuP;
  Eigen::VectorXd catVect;

  double xG = 0; 

  matRotPsi << cos(vEta[2]), -sin(vEta[2]) , 0,
    sin(vEta[2]), cos(vEta[2]), 0,
    0, 0 , 1;
  
  vEtaP = matRotPsi * vMu;

  xG = mShip->getGeoParams().xG;

  /*Sukas 2019 - Equation 16b - Coriolis matrix*/
  matC << 0, -(mShip->getM() + mShip->getMY())*vMu[2], -xG*mShip->getM()*vMu[2],
    (mShip->getM() + mShip->getMX())*vMu[2], 0, 0, xG*mShip->getM()*vMu[2], 0, 0;
  
  mShip->getHull().ComputeT(vMu, RHO_SW, mShip->getGeoParams(), mShip->getRollAngle());
  mShip->getPropeller("port").ComputeT(vMu, RHO_SW, mShip->getGeoParams());
  mShip->getRudder().ComputeT(vMu, RHO_SW, mShip->getGeoParams(), mShip->getPropeller("port"));

  /*Sukas 2019 - Equation 14*/
  mT << mShip->getHull().getT() + mShip->getPropeller().getT() + mShip->getRudder().getT();

  //Get Force from sails
  if(mShip->getSail().GetCount() > 0)
    {
      if(mShip->getSail().GetOnOff())
	{
	  mShip->getSail().ComputeT();
	  mT += mShip->getSail().getT();
	  //std::cout << "Force sail : " << mShip->getSail().getT() << std::endl;
	}
    }

  //If 2 propellers : Add force generated by the second propeller + add yaw if there are not rotated to the same speed
  if(mShip->getNumberProp() > 1)
    {
      Eigen::Vector3d fPropPort = {0,0,0};
      Eigen::Vector3d fPropStbd = {0,0,0};
      Eigen::Vector3d tYaw = {0, 0, 0};

      mShip->getPropeller("starboard").ComputeT(vMu, RHO_SW, mShip->getGeoParams());
      mT += mShip->getPropeller("starboard").getT();

      fPropStbd = mShip->getPropeller("starboard").getT();
      fPropPort = mShip->getPropeller("port").getT();

      tYaw[2] = ((1 - mShip->getPropeller().getDeductionFactor()) *
		  (mShip->getGeoParams().propSpacing/2) *
		(fPropStbd[0] - fPropPort[0]));
      mT -= tYaw;
    }

  //If 2 rudder : Add force generated by the second rudder 
  if(mShip->getNumberRud() > 1)
    {
      Eigen::Vector3d tYaw = {0, 0, 0};

      mShip->getRudder("starboard").ComputeT(vMu, RHO_SW, mShip->getGeoParams(), mShip->getPropeller("starboard"));
      mT += mShip->getRudder("starboard").getT();

      tYaw[2] = ((1 - mShip->getRudder().getDeductionFactor()) *
		 (mShip->getGeoParams().rudSpacing/2) *
		 (mShip->getRudder("port").getNormalForce() * sin(mShip->getRudder("port").getDelta()) -
		  (mShip->getRudder("starboard").getNormalForce() * sin(mShip->getRudder("starboard").getDelta()))));
      mT += tYaw;
    }


  //Add Collision
  mT += mTCol;
  
  //Add Wind drag
  mT += mTWindDrag;
  
  vMuP = mShip->getInvMatM() * (mT - (matC * vMu));/*Sukas 2019 : Equation 15*/
  
  catVect.resize(vEtaP.size() + vMuP.size());
  catVect << vEtaP, vMuP;
  
  return catVect;
}

void Solver::SetDeltaT(double aDt)
{
  mDt = aDt;
}

void Solver::Run(sTime& aTime, Eigen::Vector3d aEta, Eigen::Vector3d aMu, float aColX, float aColY, float aColN, Wind* aWind)
{
  float aDt = aTime.deltaTime;
  SetDeltaT(aDt);
  SetDataCollision(aColX, aColY, aColN);
  SetWindDrag(aWind->getAxialDrag() * MPS_TO_KTS, aWind->getLateralDrag() * MPS_TO_KTS);

  SolveRk4(aEta, aMu);
  SolveRoll();
  
}

void Solver::SetDataCollision(float aColX, float aColY, float aColN)
{
  mTCol << aColX, aColY, aColN; 
}

void Solver::SetWindDrag(float aAxialDrag, float aLateralDrag)
{
  mTWindDrag << aAxialDrag, aLateralDrag, 0; 
}

void Solver::SolveRk4(Eigen::Vector3d aEta, Eigen::Vector3d aMu)
{
  Eigen::VectorXd y = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd tmp = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd dy1 = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd dy2 = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd dy3 = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd dy4 = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  Eigen::VectorXd ySol = Eigen::VectorXd::Zero(VECTOR_SIZE_DIFF_EQ);
  
  y << aEta, aMu;

  dy1 = DiffEq(y);
  tmp = y + (0.5 * mDt * dy1);

  dy2 = DiffEq(tmp);
  tmp = y + (0.5 * mDt * dy2);

  dy3 = DiffEq(tmp);
  tmp = y + mDt * dy3;

  dy4 = DiffEq(tmp);
  ySol = y + mDt * (dy1 + 2*dy2 + 2*dy3 + dy4)/6;

  if(ySol[2] > (2*M_PI))
    ySol[2] = ySol[2] - (2*M_PI);

  if(ySol[2] < 0)
    ySol[2] = ySol[2] + (2*M_PI);
  
  mEta << ySol[0], ySol[1], ySol[2];
  mMu << ySol[3], ySol[4], ySol[5];
}


void Solver::SolveRoll(void)
{
  static double speedRoll = 0, angleRoll = 0, prevSpeedLat = 0;
  double accRoll = 0, accLat = 0;
  double c44 = 0, b44 = 0;
  double zR = 0, zH = 0;
  static bool init = false;
  
  //***** 4-DOF MathematicalModel for manoeuvring simulation including roll motion
  if(mDt > 0)
    {
      if (!init)
      {
          prevSpeedLat = mMu[1];
          init = true;
      }

      accLat = (prevSpeedLat-mMu[1])/mDt;
      zR = mShip->getGeoParams().d - (mShip->getRudder().getSpanLength()/2);
      zH = mShip->getGeoParams().d/2;
  
      //Equation (5)
      c44 = 9.81*mShip->getM()*mShip->getGeoParams().gM;
      b44 = (2 * mShip->getHull().getLinearExtinctionCoeff()/PI) * pow((9.81*mShip->getM()*(mShip->getIxx()+mShip->getJxx())), 0.5); 
  
      //Equation (4)  
      accRoll = (
		 mShip->getHull().getKh() +
		 (mShip->getGeoParams().zG * mShip->getHull().getT()[1]) -
		 (b44*speedRoll) -
		 (c44*mShip->getRollAngle()) -
		 ((zR-mShip->getGeoParams().zG)*mShip->getRudder().getT()[1]) +
		 ((zH-mShip->getGeoParams().zG)*(mShip->getMY()*accLat + mShip->getMX()*mMu[0]*mMu[2]))
		 )
	/(mShip->getIxx()+mShip->getJxx());
      
      prevSpeedLat = mMu[1];
    }
  
  speedRoll += accRoll*mDt;
  angleRoll += speedRoll*mDt;
  mShip->setRollAngle(angleRoll);
  /* std::cout << "accRoll : " << accRoll << std::endl;
  std::cout << "speedRoll : " << speedRoll << std::endl;
  std::cout << "roll angle : " << angleRoll << std::endl;
  std::cout << "Kh : " << mShip->getHull().getKh() << std::endl;
  std::cout << "Yr : " << mShip->getRudder().getT()[1] << std::endl;
  std::cout << "Yh : " << mShip->getHull().getT()[1] << std::endl;*/
}

Eigen::Vector3d Solver::getEta(void) const {return mEta;}
Eigen::Vector3d Solver::getMu(void) const {return mMu;}
